# Generated by Django 3.0.2 on 2020-02-12 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDB', models.BooleanField()),
                ('dataset', models.FileField(blank=True, upload_to='dataset/')),
                ('dbUrl', models.CharField(blank=True, max_length=256)),
                ('tables', models.CharField(blank=True, max_length=256)),
                ('table', models.CharField(blank=True, max_length=256)),
                ('columns', models.CharField(max_length=256)),
                ('mode', models.CharField(max_length=256)),
                ('labelsType', models.CharField(blank=True, max_length=256)),
                ('labelsFile', models.FileField(blank=True, upload_to='labels/')),
                ('labelsColumn', models.CharField(blank=True, max_length=256)),
                ('labelsTable', models.CharField(blank=True, max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('transforms', models.CharField(max_length=256)),
                ('pipeline', models.FileField(blank=True, upload_to='model/')),
                ('runDB', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResultScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throughput', models.FloatField()),
                ('executionTime', models.FloatField()),
                ('size', models.IntegerField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msp.Scenario')),
            ],
        ),
    ]
