# Generated by Django 3.0.2 on 2020-02-14 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='dbUrl',
            new_name='db_url',
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='isDB',
            new_name='is_db',
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='labelsColumn',
            new_name='labels',
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='runDB',
            new_name='run_db',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='labelsFile',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='labelsTable',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='labelsType',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='tables',
        ),
        migrations.AddField(
            model_name='scenario',
            name='labels_type',
            field=models.CharField(blank=True, choices=[('column', 'Column'), ('table', 'Table'), ('file', 'File')], max_length=256),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='mode',
            field=models.CharField(choices=[('train', 'Train'), ('test', 'Test')], max_length=256),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset', to='msp.Document'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline', to='msp.Document'),
        ),
    ]
