# Generated by Django 3.0.2 on 2020-02-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msp', '0002_auto_20200214_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file_path',
            new_name='filename',
        ),
    ]
