# Generated by Django 3.0.2 on 2020-02-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msp', '0003_auto_20200214_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='validation',
            field=models.FloatField(default=0),
        ),
    ]
