# Generated by Django 3.0.2 on 2020-02-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msp', '0004_scenario_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='metric',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
