# Generated by Django 3.0.2 on 2020-02-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msp', '0005_scenario_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='db_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='labels',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='labels_type',
            field=models.CharField(blank=True, choices=[('column', 'Column'), ('table', 'Table'), ('file', 'File')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='table',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='transforms',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
