# Generated by Django 3.0.2 on 2020-03-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msp', '0007_auto_20200218_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultscenario',
            old_name='executionTime',
            new_name='execution_time',
        ),
        migrations.RemoveField(
            model_name='resultscenario',
            name='size',
        ),
        migrations.AddField(
            model_name='resultscenario',
            name='file_result',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='resultscenario',
            name='query',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='resultscenario',
            name='score',
            field=models.FloatField(default=11),
            preserve_default=False,
        ),
    ]
