# Generated by Django 3.0.2 on 2020-03-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msp', '0008_auto_20200304_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultscenario',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
