# Generated by Django 3.0.2 on 2021-05-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msp', '0010_auto_20200623_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='optimizer',
            field=models.BooleanField(default=False),
        ),
    ]
